// Object to serve as the export scope
const exports = {};

// Handles Node style require statements generated by TypeScript
function require(file) {
	var script = document.createElement('script');
    script.type = 'application/javascript';
	script.src = file + '.js';
	document.getElementsByTagName('head')[0].appendChild(script);
	return this;
}
